Develop
jklarson/volttron pull request #1
Opened 2020-06-01 19:07 UTC by john-zapanta-jr

# Description

GPIO Driver, example configs, documentation, and pytest added.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Unit test using mock pins added.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2020-06-09 16:20 UTC, jklarson requested changes

2020-06-09 16:20 UTC, jklarson commented on services/core/MasterDriverAgent/master_driver/interfaces/gpio.py
> +        self.registers = {
This may not be required ( and in fact may be something I need to change for Ecobee). In Ecobee this was done for register types that returned data types that didn't match the existing register types (for example: program and vacation endpoints return dictionary structures - that said the holds and settings from Ecobee should probably be int registers).

2020-06-09 16:20 UTC, jklarson commented on services/core/MasterDriverAgent/master_driver/interfaces/gpio.py
> +        self.config_dict = config_dict
I received feedback from Craig that we should be using self.config.update(config_dict) here on the updates I'm doing for the Ecobee driver.

2020-06-09 16:20 UTC, jklarson commented on services/core/MasterDriverAgent/master_driver/interfaces/gpio.py
> +                raise ValueError(
I think we could merge this conditional in the try and capture both states with the error message. Ideally I think we'd have something describing valid pin numbers: "Registry config entry {} provided an invalid pin. GPIO supports Broadcom pins as integers from 2 to 27" or something to that effect.

2020-06-09 16:20 UTC, jklarson commented on services/core/MasterDriverAgent/master_driver/interfaces/gpio.py
> +                reg["Device Type"] = "output"
Lets use something like string.lower() to try to capture more of the potential input by a user (e.i. "Output" would fail here, but could easily be checked for with .lower() )

2020-06-09 16:20 UTC, jklarson commented on services/core/MasterDriverAgent/master_driver/interfaces/gpio.py
> +                if not (reg.get("Pull Up") is None):
This looks like it should be reg.get("Pull Up") is not None:

2020-06-09 16:20 UTC, jklarson commented on services/core/MasterDriverAgent/master_driver/interfaces/gpio.py
> +            elif reg["Device Type"] == "output" or reg["Device Type"] == "digital_output":
Lets have another .lower() style comparison here.

2020-06-09 16:20 UTC, jklarson commented on services/core/MasterDriverAgent/master_driver/interfaces/gpio.py
> +        if isinstance(value, dict):
should this work with read-only points?

2020-06-09 16:20 UTC, jklarson commented on services/core/MasterDriverAgent/master_driver/interfaces/gpio.py
> +        Helper function for performing a callback that publishes to the message bus.
I think here we can use self.driver.publish_cov_value(self.device.value, self.point_name)

2020-06-09 16:20 UTC, jklarson commented on docs/source/core_services/drivers/driver_configuration/gpio_driver.rst
> +    Pin - The broadcom pin number of the GPIO pin the device is connected to.
Broadcom should be capitalized

2020-06-09 16:20 UTC, jklarson commented on docs/source/core_services/drivers/driver_configuration/gpio_driver.rst
> +::
Try capturing output as displayed from the listener agent.

2020-06-09 16:20 UTC, jklarson commented on services/core/MasterDriverAgent/tests/test_gpio_driver.py
> +def drive_low(abort_pin):
We should have tests which also test failure conditions. What happens if we provide illegal values, etc. Pytest.raises and other tools can be handy for this.

2020-06-09 16:58 UTC, john-zapanta-jr commented on services/core/MasterDriverAgent/master_driver/interfaces/gpio.py
> +                reg["Device Type"] = "output"
It's actually not a conditional here, it's an assignment to the value "output" by default.

2020-06-09 23:58 UTC, john-zapanta-jr commented on services/core/MasterDriverAgent/master_driver/interfaces/gpio.py
> +        if isinstance(value, dict):
Input points are read only, but have actions that need to be accessed through set point - i.e. call backs. I don't let values get set for read only points though.

2020-06-22 18:19 UTC, jklarson commented on services/core/MasterDriverAgent/tests/test_gpio_driver.py
> +    with pytest.raises(ValueError):
Lets break out the failure cases into their own test and use pytest.mark.parametrize to improve code-reuse.

2020-06-23 16:58 UTC, craigpnnl commented on docs/source/core_services/drivers/driver_configuration/gpio_driver.rst
> +The GPIO driver is an implementation of a VOLTTRON driver frame work Interface. An instance of a VOLTTRON Interface
framework not frame work

2020-07-17 17:46 UTC, merged